In [42]:
import pandas as pd
import numpy as np
import tensorflow as tf


train_data = pd.read_csv('../data/train_data.csv')
test_data = pd.read_csv('../data/blind_data.csv')

In [55]:
test_data

Unnamed: 0 Formation Well Name   Depth      GR  ILD_log10  DeltaPHI  \
0             0     A1 SH    STUART  2808.0  66.276      0.630     3.300   
1             1     A1 SH    STUART  2808.5  77.252      0.585     6.500   
2             2     A1 SH    STUART  2809.0  82.899      0.566     9.400   
3             3     A1 SH    STUART  2809.5  80.671      0.593     9.500   
4             4     A1 SH    STUART  2810.0  75.971      0.638     8.700   
..          ...       ...       ...     ...     ...        ...       ...   
825         825      C SH  CRAWFORD  3158.5  86.078      0.554     5.040   
826         826      C SH  CRAWFORD  3159.0  88.855      0.539     5.560   
827         827      C SH  CRAWFORD  3159.5  90.490      0.530     6.360   
828         828      C SH  CRAWFORD  3160.0  90.975      0.522     7.035   
829         829      C SH  CRAWFORD  3160.5  90.108      0.513     7.505   

      PHIND     PE  NM_M  RELPOS  Facies  
0    10.650  3.591     1   1.000       3  
1    11.950  3.341     1   0.978       3  
2    13.600  3.064     1   0.956       3  
3    13.250  2.977     1   0.933       3  
4    12.350  3.020     1   0.911       3  
..      ...    ...   ...     ...     ...  
825  16.150  3.161     1   0.639       3  
826  16.750  3.118     1   0.611       3  
827  16.780  3.168     1   0.583       3  
828  16.995  3.154     1   0.556       3  
829  17.595  3.125     1   0.528       3  

[830 rows x 12 columns]

In [58]:
x = np.array(train_data.drop(['Facies','Formation','Well Name','Depth','NM_M','RELPOS'], axis=1))

In [46]:
x_test = np.array(test_data.drop(['Facies','Formation','Well Name','Depth','NM_M','RELPOS'], axis=1))

In [60]:
x_test

array([[0.0000e+00, 6.6276e+01, 6.3000e-01, 3.3000e+00, 1.0650e+01,
        3.5910e+00],
       [1.0000e+00, 7.7252e+01, 5.8500e-01, 6.5000e+00, 1.1950e+01,
        3.3410e+00],
       [2.0000e+00, 8.2899e+01, 5.6600e-01, 9.4000e+00, 1.3600e+01,
        3.0640e+00],
       ...,
       [8.2700e+02, 9.0490e+01, 5.3000e-01, 6.3600e+00, 1.6780e+01,
        3.1680e+00],
       [8.2800e+02, 9.0975e+01, 5.2200e-01, 7.0350e+00, 1.6995e+01,
        3.1540e+00],
       [8.2900e+02, 9.0108e+01, 5.1300e-01, 7.5050e+00, 1.7595e+01,
        3.1250e+00]])

In [47]:
y_train = np.array(train_data['Facies'].values)-1
y_test = np.array(test_data['Facies'].values)-1

In [48]:
x_test

array([[0.0000e+00, 6.6276e+01, 6.3000e-01, 3.3000e+00, 1.0650e+01,
        3.5910e+00],
       [1.0000e+00, 7.7252e+01, 5.8500e-01, 6.5000e+00, 1.1950e+01,
        3.3410e+00],
       [2.0000e+00, 8.2899e+01, 5.6600e-01, 9.4000e+00, 1.3600e+01,
        3.0640e+00],
       ...,
       [8.2700e+02, 9.0490e+01, 5.3000e-01, 6.3600e+00, 1.6780e+01,
        3.1680e+00],
       [8.2800e+02, 9.0975e+01, 5.2200e-01, 7.0350e+00, 1.6995e+01,
        3.1540e+00],
       [8.2900e+02, 9.0108e+01, 5.1300e-01, 7.5050e+00, 1.7595e+01,
        3.1250e+00]])

In [22]:
y_train=tf.keras.utils.to_categorical(y_train,9)
y_test=tf.keras.utils.to_categorical(y_test,9)

In [23]:
y_train = tf.keras.utils.to_categorical(y_train,9)
y_test = tf.keras.utils.to_categorical(y_test,9)

In [26]:
x_train = np.zeros_like(x)

In [29]:
x_train[:,:] = x[:,:]

In [41]:
x_test

array([[0.0000e+00, 6.6276e+01, 6.3000e-01, 3.3000e+00, 1.0650e+01,
        3.5910e+00],
       [1.0000e+00, 7.7252e+01, 5.8500e-01, 6.5000e+00, 1.1950e+01,
        3.3410e+00],
       [2.0000e+00, 8.2899e+01, 5.6600e-01, 9.4000e+00, 1.3600e+01,
        3.0640e+00],
       ...,
       [8.2700e+02, 9.0490e+01, 5.3000e-01, 6.3600e+00, 1.6780e+01,
        3.1680e+00],
       [8.2800e+02, 9.0975e+01, 5.2200e-01, 7.0350e+00, 1.6995e+01,
        3.1540e+00],
       [8.2900e+02, 9.0108e+01, 5.1300e-01, 7.5050e+00, 1.7595e+01,
        3.1250e+00]])

In [39]:
test_temp = x_test[:,:]

In [40]:
x_test = np.zeros_like(test_temp)
x_test[:,:] = test_temp[:,:]